name: Advent of Code 2017

on:
  push:
    branches:
      - master
    paths:
      - "2017/**"
  pull_request:
    paths:
      - "2017/**"

jobs:
  build-2017:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "2017"

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm ci
      - run: npm test
        env:
          CI: true
