name: Advent of Code 2017

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/2017.yml
      - 2017/**
  pull_request:
    paths:
      - .github/workflows/2017.yml
      - 2017/**

jobs:
  build-2017:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "2017"

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: npm ci

      - run: npm test
        env:
          CI: true
