name: Advent of Code 2019

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/2019.yml
      - 2019/**
  pull_request:
    paths:
      - .github/workflows/2019.yml
      - 2019/**

jobs:
  build-2019:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "2019"

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: true

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test
