name: Advent of Code 2021

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/2021.yml
      - 2021/**
  pull_request:
    paths:
      - .github/workflows/2021.yml
      - 2021/**

jobs:
  build-2021:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: "2021"

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: true

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build -j 4

      - name: Test
        run: ctest --test-dir build -j 4
